### ISSUE TITLE
Expected stderr: "exception Exceptions.LocalAssignTypeMismatch("B", "C")"

### ISSUE THREAD

**Issue by six5532one** [DavidWatkins/DiceLanguage#130]
1 class A {}
  2 
  3 class B extends A {}
  4 
  5 class C {}
  6 
  7 class test {
  8     public void main(char[][] args) {
  9         class A myBObj = new B();
 10         class B mySecondBObj = new C();
 11     }
 12 }

**Comment by KhaledAtef** [comment]
Added.
