### ISSUE TITLE
Decide whether to promote all ints to floats in binops

### ISSUE THREAD

**Issue by KhaledAtef** [DavidWatkins/DiceLanguage#52]

**Comment by KhaledAtef** [comment]
In the case of adding floats to ints, did we decide on promoting the ints to floats? Originally, we said we'll just take whatever comes first, but I couldn't remember what we decided on.

**Comment by six5532one** [comment]
I thought we decided to promote ints to floats (for binops) because when we got together last time, we tried out the llvm library's build_add function with an int and a "float" by casting the int to const_double, then using const_uitofp

**Comment by DavidWatkins** [comment]
Ah gotcha. But if we have the addition of two integers, it stays type int, correct?

**Comment by six5532one** [comment]
In the current implementation, yup indeed:
https://github.com/DavidWatkins/Dice/blob/emily/Compiler/analyzer.ml#L115
