### ISSUE TITLE
Object creation: this should raise "ConstructorNotFound: Foo.constructor.int.bool.char.float"

### ISSUE THREAD

**Issue by six5532one** [DavidWatkins/DiceLanguage#60]
class Foo {
constructor(char c, float f) {}
constructor(bool b, char c, float f) {}
}

class test {
public void main(char[][] args) {
int mya = 2;
bool myb = false;
char myc = 'z';
float myf = 3.5;
class Foo myFooObj = new Foo(mya, myb, myc, myf);
}
}

**Comment by KhaledAtef** [comment]
Added.
