### ISSUE TITLE
object creation: This should throw no exceptions

### ISSUE THREAD

**Issue by six5532one** [DavidWatkins/DiceLanguage#61]
class Bar {
  2     constructor(char c, float f) {}
  3     constructor(bool b, char c, float f) {}
  4 }
  5 
  6 class Foo {
  7    constructor(bool a, int b) {}
  8    constructor(int a, bool b, char c, float f) {}
  9 }
 10 
 11 class test {
 12     public void main(char[][] args) {
 13         int mya = 2;
 14         bool myb = false;
 15         char myc = 'z';
 16         float myf = 3.5;
 17         class Foo myFooObj = new Foo(mya, myb, myc, myf);
 18     }
 19 }

**Comment by KhaledAtef** [comment]
Added.
