### ISSUE TITLE
Compiler doesn't allow formal to be an object

### ISSUE THREAD

**Issue by six5532one** [DavidWatkins/DiceLanguage#62]
Compiling this results in the following error:
File "test-localobj-em.dice", line 7, character 12, Syntax Error, token ID(Bar)

class Bar {
  2     constructor(char c, float f) {}
  3     constructor(bool b, char c, float f) {}
  4 }
  5 
  6 class Foo {
  7    constructor(Bar b) {}
  8    constructor(int a, bool b, char c, float f) {}
  9 }
 10 
 11 class test {
 12     public void main(char[][] args) {
 13         char myc = 'z';
 14         float myf = 4.5;
 15         class Bar myb = new Bar(myc, myf);
 16     }
 17 }

 class Bar {
  2     constructor(char c, float f) {}
  3     constructor(bool b, char c, float f) {}
  4 }
  5 

```

Whereas this compiles successfully:
  6 class Foo {
  8    constructor(int a, bool b, char c, float f) {}
  9 }
 10 
 11 class test {
 12     public void main(char[][] args) {
 13         char myc = 'z';
 14         float myf = 4.5;
 15         class Bar myb = new Bar(myc, myf);
 16     }
 17 }
```

**Comment by DavidWatkins** [comment]
Actually it is accepted by the parser, you just need to make sure all references to classes start with "class". i.e.

``` java
class Bar {
    constructor(char c, float f) {}
    constructor(bool b, char c, float f) {}
}

class Foo {
   constructor(class Bar b) {}
   constructor(int a, bool b, char c, float f) {}
}

class test {
    public void main(char[][] args) {
        char myc = 'z';
        float myf = 4.5;
        class Bar myb = new Bar(myc, myf);
    }
}
```
