### ISSUE TITLE
object creation: this should raise no exceptions

### ISSUE THREAD

**Issue by six5532one** [DavidWatkins/DiceLanguage#63]
class Bar {
  2     constructor(char c, float f) {}
  3     constructor(bool b, char c, float f) {}
  4 }
  5 
  6 class Foo {
  7    constructor(int a, bool b, char c, float f) {}
  8 }
  9 
 10 class test {
 11     public void main(char[][] args) {
 12         char myc = 'z';
 13         float myf = 4.5;
 14         class Bar myb = new Bar(myc, myf);
 15         class Foo myFooObj = new Foo(5, true, myc, myf);
 16     }
 17 }

**Comment by KhaledAtef** [comment]
Added.
