### ISSUE TITLE
Use of Delete

### ISSUE THREAD

**Issue by DavidWatkins** [DavidWatkins/DiceLanguage#87]
class test {

public void main() {

int[] a = new int[10];
delete a;

class test b = new test();
delete b;

delete (new test());

int[][] a = new int[10][20];
delete a[2]; (\* Not sure if this would delete the entire 1-d array _)
(_ Probably should make this undefined *)

}
}

**Comment by KhaledAtef** [comment]
khal@khal-VirtualBox:~/Dice$ ./dice -c Test\ Suite/Compiler_Test_Suite/test-delete.dice 
Fatal error: exception Exceptions.ArrayLargerThan1Unsupported
Raised at file "hashtbl.ml", line 136, characters 19-28
